version: 2.1
commands: # a reusable command with parameters
  greeting:
    parameters:
      catch-phrase:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.catch-phrase>>"
jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello!"
  say-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo World!"
  print-var-value:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print 'test' from the env file in the project"
          command: "echo ${TEST_VAR}"
  save-hello-world-output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "add 'hello world' to a file called output.txt"
          command: "echo 'hello world' > ~/output.txt"
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print-output-file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "output 'hello world' to a file called output.txt"
          command: "cat ~/output.txt"
  say-hello-habibi-from-the-command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - greeting:
          catch-phrase: "7bibi"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello
      - print-var-value
      - save-hello-world-output
      - print-output-file:
          requires:
            - save-hello-world-output
      - say-hello-habibi-from-the-command
