version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  # Orchestrate or schedule a set of jobs
jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello!"
  say-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo World!"
workflows:
  say-hello-world-workflow:
    jobs:
      - say-hello
      - say-world
